### ISSUE TITLE
Merge plata/ublue-surface with this repo

### ISSUE THREAD

**Issue by plata** [ublue-os/surface#23]
I wasn't aware that this repository exists. I did some work in https://github.com/plata/ublue-surface do provide a tailored Plasma Mobile experience for the Surface Go.

Regarding repository structure: How to handle different Surface variants/DEs? The Surface laptops should have the desktop GNOME/Plasma but for the tablets we should have Phosh/GNOME Mobile Shell/Plasma Mobile.

**Comment by castrojo** [comment]
Sorry no one responded to this issue! I'm not sure how we should handle the tablets but we can start with the desktop stuff, please feel free to PR in fixes that you might need, I don't have a Surface device yet but hoping to get one soon!

**Comment by castrojo** [comment]
Ok we got some PRs in and these images are in much better shape now, I went ahead and filed a new issue for the flavor discussion, thanks!
