### ISSUE TITLE
Feature Request: Add Surface Aggregator to initramfs

### ISSUE THREAD

**Issue by keplersj** [ublue-os/surface#25]
If a user configures their install with Full Disk Encryption on a device using the Surface Aggregator Module, they are unable to enter their passkey with the built in keyboard with the default Silverblue initramfs. After reading [linux-surface: Disk Encryption](https://github.com/linux-surface/linux-surface/wiki/Disk-Encryption) I was able to resolve this by writing the following to `/etc/dracut.conf.d/surface.conf` and running `rpm-ostree initramfs --enable`:

```conf
add_drivers+="surface_hid_core surface_hid surface_aggregator_registry surface_aggregator surface_aggregator_hub pinctrl_amd"
```

I don't know if this configuration is possible in the image generation process, but if it is it would make the process of bringing up a Silverblue/uBlue install on a Surface using the SAM (like my Surface Laptop 3 AMD) much easier.

**Comment by castrojo** [comment]
I can do the file no problem, but no idea on the initramfs, cc @ublue-os/approver
